### ISSUE TITLE
Vagrant up fails

### ISSUE THREAD

**Issue by marcin-kasinski** [OpenStackCookbook/vagrant-openstack#23] opened 2018-02-10 19:14 UTC
I tried your code with no success.

Vagrant up exits with error:

TASK [command] *****************************************************************
fatal: [compute-01]: FAILED! => {"changed": true, "cmd": ["systemctl", "restart", "libvirtd"], "delta": "0:00:00.002491", "end": "2018-02-10 18:49:48.425390", "failed": true, "rc": 5, "start": "2018-02-10 18:49:48.422899", "stderr": "Failed to restart libvirtd.service: Unit libvirtd.service not found.", "stdout": "", "stdout_lines": [], "warnings": []}

PLAY RECAP *********************************************************************
compute-01                 : ok=19   changed=8    unreachable=0    failed=1
controller-01              : ok=33   changed=17   unreachable=0    failed=0

Ansible failed to complete successfully. Any error output should be
visible above. Please fix these errors and try again.
[1]+  Done                    VirtualBox

Then I tried vagrant up again.

After that I got another error:

    openstack-client: Installing collected packages: shade
    openstack-client: Successfully installed shade-1.26.0
    openstack-client: You are using pip version 8.1.2, however version 9.0.1 is available.
    openstack-client: You should consider upgrading via the 'pip install --upgrade pip' command.
root@mainserver:/vagrantprojects/vagrant-openstack# pip install --upgrade pip
Requirement already up-to-date: pip in /usr/local/lib/python2.7/dist-packages
root@mainserver:/vagrantprojects/vagrant-openstack#

**Comment by it-praktyk** [comment] 2018-02-10 19:22
Hi @marcin-kasinski,
your issue was resolved by me - as I believe - in the pull request #19.

The first error is caused by the lack of the libvirt-bin package. 

What I can propose you that - before pull request proposed by me will be merged - is to use the code from the branch [All_PR_20180205-06](https://github.com/it-praktyk/vagrant-openstack/tree/All_PR_20180205-06) in my fork. It should contain - not in an exact order - all changes from pull request prepared by me.

Please let us know if the updated code performs well.

**Comment by marcin-kasinski** [comment] 2018-02-10 19:38
root@mainserver:/vagrantprojects# git clone --branch All_PR_20180205-06 https://github.com/OpenStackCookbook/vagrant-openstack.git
Cloning into 'vagrant-openstack'...
fatal: Remote branch All_PR_20180205-06 not found in upstream origin
root@mainserver:/vagrantprojects#

**Comment by it-praktyk** [comment] 2018-02-10 19:42
What did I write? ;-)

> is to use the code from the branch All_PR_20180205-06 in my fork.

`
git remote add it-praktyk https://github.com/it-praktyk/vagrant-openstack.git
git fetch --all
git branch --track All_PR_20180205-06 it-praktyk/All_PR_20180205-06
git checkout All_PR_20180205-06
`

**Comment by marcin-kasinski** [comment] 2018-02-10 21:50
Now I get:

 openstack-client: You are using pip version 8.1.2, however version 9.0.1 is available.
    openstack-client: You should consider upgrading via the 'pip install --upgrade pip' command.



root@mainserver:/vagrantprojects/vagrant-openstack# pip install --upgrade pip
Requirement already up-to-date: pip in /usr/local/lib/python2.7/dist-packages


root@mainserver:/vagrantprojects/vagrant-openstack# pip --version
pip 9.0.1 from /usr/local/lib/python2.7/dist-packages (python 2.7)

**Comment by it-praktyk** [comment] 2018-02-10 21:55
```
openstack-client: You are using pip version 8.1.2, however version 9.0.1 is available.
openstack-client: You should consider upgrading via the 'pip install --upgrade pip' command.
```

Solution updated by me provision the OpenStack environment using Ansible installed inside of the virtual machine named "openstack-client".

You can ignore warnings about the pip version.

**Comment by it-praktyk** [comment] 2018-02-10 21:58
@uksysadmin,
what do you think about [suppressing pip upgrade warnings](https://stackoverflow.com/questions/46288847/how-to-suppress-pip-upgrade-warning)?

**Comment by uksysadmin** [comment] 2018-02-21 15:38
Changes merged!

**Closed by uksysadmin** 2018-02-21 15:38 UTC
